name: Binge Read
title: Binge Read | Mein Lee Netflix-themed personal blog
description: Mein Lee's personal website using a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
  - berkeley
  - ucberkeley
  - datascience
  - swe
  - aws
  - netflix
  - design
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: meinlee@berkeley.edu
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
show_hero: true
# Amount of post to show per page
paginate: 12
